# Generated by Django 4.0.4 on 2022-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='observation',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
